project_name: hawkwing

before:
  hooks:
    - go mod tidy

builds:
  - main: ./hawkwing/
    binary: hawkwing
    ldflags:
      - -s -w -X github.com/hawkv6/hawkwing/internal/version.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dockers:
  - use: buildx
    dockerfile: ./build/package/Dockerfile
    image_templates:
      - "ghcr.io/hawkv6/hawkwing:latest"
      - "ghcr.io/hawkv6/hawkwing:{{ .Tag }}"
