// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/intent.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IntentServiceClient is the client API for IntentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntentServiceClient interface {
	GetIntentDetails(ctx context.Context, in *Intent, opts ...grpc.CallOption) (*Response, error)
}

type intentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentServiceClient(cc grpc.ClientConnInterface) IntentServiceClient {
	return &intentServiceClient{cc}
}

func (c *intentServiceClient) GetIntentDetails(ctx context.Context, in *Intent, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.IntentService/GetIntentDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntentServiceServer is the server API for IntentService service.
// All implementations must embed UnimplementedIntentServiceServer
// for forward compatibility
type IntentServiceServer interface {
	GetIntentDetails(context.Context, *Intent) (*Response, error)
	mustEmbedUnimplementedIntentServiceServer()
}

// UnimplementedIntentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntentServiceServer struct {
}

func (UnimplementedIntentServiceServer) GetIntentDetails(context.Context, *Intent) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntentDetails not implemented")
}
func (UnimplementedIntentServiceServer) mustEmbedUnimplementedIntentServiceServer() {}

// UnsafeIntentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentServiceServer will
// result in compilation errors.
type UnsafeIntentServiceServer interface {
	mustEmbedUnimplementedIntentServiceServer()
}

func RegisterIntentServiceServer(s grpc.ServiceRegistrar, srv IntentServiceServer) {
	s.RegisterService(&IntentService_ServiceDesc, srv)
}

func _IntentService_GetIntentDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Intent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServiceServer).GetIntentDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IntentService/GetIntentDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServiceServer).GetIntentDetails(ctx, req.(*Intent))
	}
	return interceptor(ctx, in, info, handler)
}

// IntentService_ServiceDesc is the grpc.ServiceDesc for IntentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.IntentService",
	HandlerType: (*IntentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIntentDetails",
			Handler:    _IntentService_GetIntentDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/intent.proto",
}
