// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package client

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tcIn6Addr struct{ In6U struct{ U6Addr8 [16]uint8 } }

type tcServerLookupKey struct {
	Addr tcIn6Addr
	Port uint16
}

type tcServerLookupValue struct {
	Sidlist     [10]tcIn6Addr
	SidlistSize int32
}

// loadTc returns the embedded CollectionSpec for tc.
func loadTc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc: %w", err)
	}

	return spec, err
}

// loadTcObjects loads tc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcObjects
//	*tcPrograms
//	*tcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcSpecs struct {
	tcProgramSpecs
	tcMapSpecs
}

// tcSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcProgramSpecs struct {
	ClientEgress *ebpf.ProgramSpec `ebpf:"client_egress"`
}

// tcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcMapSpecs struct {
	ClientInnerMap     *ebpf.MapSpec `ebpf:"client_inner_map"`
	ClientLookupMap    *ebpf.MapSpec `ebpf:"client_lookup_map"`
	ClientOuterMap     *ebpf.MapSpec `ebpf:"client_outer_map"`
	ClientReverseMap   *ebpf.MapSpec `ebpf:"client_reverse_map"`
	ServerLookupMap    *ebpf.MapSpec `ebpf:"server_lookup_map"`
	ServerTempValueMap *ebpf.MapSpec `ebpf:"server_temp_value_map"`
}

// tcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcObjects struct {
	tcPrograms
	tcMaps
}

func (o *tcObjects) Close() error {
	return _TcClose(
		&o.tcPrograms,
		&o.tcMaps,
	)
}

// tcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcMaps struct {
	ClientInnerMap     *ebpf.Map `ebpf:"client_inner_map"`
	ClientLookupMap    *ebpf.Map `ebpf:"client_lookup_map"`
	ClientOuterMap     *ebpf.Map `ebpf:"client_outer_map"`
	ClientReverseMap   *ebpf.Map `ebpf:"client_reverse_map"`
	ServerLookupMap    *ebpf.Map `ebpf:"server_lookup_map"`
	ServerTempValueMap *ebpf.Map `ebpf:"server_temp_value_map"`
}

func (m *tcMaps) Close() error {
	return _TcClose(
		m.ClientInnerMap,
		m.ClientLookupMap,
		m.ClientOuterMap,
		m.ClientReverseMap,
		m.ServerLookupMap,
		m.ServerTempValueMap,
	)
}

// tcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcPrograms struct {
	ClientEgress *ebpf.Program `ebpf:"client_egress"`
}

func (p *tcPrograms) Close() error {
	return _TcClose(
		p.ClientEgress,
	)
}

func _TcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_bpfel.o
var _TcBytes []byte
