---
hawkeye:
  hostname: hawkeye.hawk.net
  port: 1234
services:
  wb.hawk.net:
    - intent: high-bandwidth
      port: 80 # 50 00
      sid: 
        - fcbb:bb00:1::1
        - fcbb:bb00:3::1
    - intent: low-bandwidth
      port: 8080 # 90 1f
  wc.hawk.net:
    - intent: high-bandwidth
      port: 1433 # 99 05
      sid: 
        - fcbb:bb00:1::1
        - fcbb:bb00:3::1