---
hawkeye:
  hostname: fcbb:cc00:5::f # hawkeye.hawk.net
  port: 5001
services:
  webserver-b:
    domain_name: wb.hawk.net
    applications:
      - port: 80
        sid:
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2
      - port: 8080
        intents:
          - intent: sfc
            functions:
              - fw
              - ids
          - intent: flex-algo
            flex_algo_number: 1
          - intent: low-latency
          - intent: low-bandwidth
            min_value: 1
            max_value: 9
  webserver-c:
    domain_name: wc.hawk.net
    applications:
      - port: 1433
        sid:
          - fcbb:bb00:2::2
          - fcbb:bb00:4::2
  webserver-d:
    ipv6_addresses:
      - fcbb:cc00:4::a
      - fcbb:cc00:4::b
      - fcbb:cc00:4::c
    applications:
      - port: 443
        intents:
          - intent: high-bandwidth
            min_value: 1
            max_value: 9